version: "3"

services:

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  server:
    image: firebase
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: npm start
    environment:
      NODE_ENV: development
      HOST: "0.0.0.0"
      PORT: "${PORT}"
      POSTGRES_URL: "${POSTGRES_URL}"
      JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
    depends_on:
      - postgres
    links:
      - postgres

