version: "3"

services:

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    sysctls:
      net.core.somaxconn: "65535"

  server:
    image: session-ws
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: npm start
    environment:
      NODE_ENV: development
      HOST: "0.0.0.0"
      PORT: "${PORT}"
      POSTGRES_URL: "${POSTGRES_URL}"
      REDIS_URL: "${REDIS_URL}"
      SESSION_SECRET_KEY: "${SESSION_SECRET_KEY}"
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis

